5688.dev News Page aded Styles to Top block
tymoshchuk-o/drupal pull request #41
Opened 2022-12-22 15:41 UTC by tymoshchuk-o

https://redmine.devbranch.work/issues/5688

2022-12-26 08:48 UTC, Y0r requested changes

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/src/scss/_main-news.scss
> +
?

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/block--block-content--custom-site-logo--full.html.twig
> + %}
CS

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/block--block-content--custom-site-logo--full.html.twig
> +   </div>
Why?

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/field/field--node--created--posts.html.twig
> +</span>
CS

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/node--posts--top-post.html.twig
> +] %}
CS

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/node--posts--top-post.html.twig
> +</article>
CS

2022-12-26 08:48 UTC, Y0r commented on web/themes/custom/green_theme/templates/paragraph--follow-us-item-block--default.html.twig
> +      </a>
CS

2022-12-26 14:24 UTC, tymoshchuk-o commented on web/themes/custom/green_theme/templates/block--block-content--custom-site-logo--full.html.twig
> +   </div>
Different logo from the footer

2022-12-28 08:49 UTC, Y0r approved these changes

2022-12-28 09:14 UTC, merged